evals: tweak an occasionally failing evaluation case
```
FAILED evals/features/cve/test_suggest_cwe.py::test_eval_suggest_cwe - AssertionError: Unsatisfied assertion(s):
suggest-cwe-for-CVE-2025-57803: SuggestCweEvaluator: score below threshold: -0.2250 < 0.1, reason: got ['CWE-190', 'CWE-805'], expected ['CWE-787', 'CWE-131']
```

Despite CWE-190 was used in production OSIDB, it was not included
in the expected values.

Related: https://github.com/RedHatProductSecurity/aegis-ai/pull/558