fix: set POST request timeout in `osvdev` tool
This eliminates the following SAST finding reported by Coverity:
```
Error: SIGMA.connection_timeout_disabled (CWE-400):
src/aegis_ai/tools/osvdev/__init__.py:79: Sigma main event: The `timeout` attribute is undefined or is set to `None`, which disables the timeouts on streaming connections. This makes it easier for an attacker to launch a Denial-of-Service (DoS) attack. Other problems can include large numbers of inactive connections that aren't being closed and running out of ephemeral ports.
src/aegis_ai/tools/osvdev/__init__.py:79: remediation: Explicitly set the `timeout` attribute to a value greater than 0.
   77|           url = f"{self.base_url}/{endpoint.lstrip('/')}"
   78|           try:
   79|->             response = self._session.post(url, json=data)
   80|               response.raise_for_status()
   81|               # The query endpoints return an empty body with a 200 OK if no vulns are found.
```

Related: https://issues.redhat.com/browse/AEGIS-78