aegis: do not override `AnthropicModelSettings`
Based on the output of `make eval`, the settings is not needed.
Moreover, when used with `pydantic-ai-0.4.0`, it broke the Anthropic
support in aegis completely:
```
pydantic_ai.exceptions.ModelHTTPError: status_code: 400, model_name: claude-3-5-sonnet-20241022, body: {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Thinking may not be enabled when tool_choice forces tool use.'}}
```

Fixes: commit aebd787273d78449c4f5482f193fcd5cb1ac17a7
Fixes: https://github.com/RedHatProductSecurity/aegis/issues/61
PR: https://github.com/RedHatProductSecurity/aegis/pull/62