fix: work around inability to install gcc on `ubi10-minimal`
Enable CentOS 10 Stream repos temporarily so that gcc and its
dependencies can be resolved:
```
error: Could not depsolve transaction; 2 problems detected:
 Problem 1: package gcc-14.3.1-4.4.el10.x86_64 from ubi-10-appstream-rpms requires glibc-devel >= 2.2.90-12, but none of the providers can be installed
  - conflicting requests
  - nothing provides glibc = 2.39-124.el10_2 needed by glibc-devel-2.39-124.el10_2.x86_64 from ubi-10-appstream-rpms
 Problem 2: package tar-2:1.35-11.el10.x86_64 from ubi-10-baseos-rpms requires libc.so.6(GLIBC_2.38)(64bit), but none of the providers can be installed
  - package tar-2:1.35-11.el10.x86_64 from ubi-10-baseos-rpms requires rtld(GNU_HASH), but none of the providers can be installed
  - package glibc-2.39-121.el10_2.x86_64 from @System requires (glibc-gconv-extra(x86-64) = 2.39-121.el10_2 if redhat-rpm-config), but none of the providers can be installed
  - package glibc-2.39-121.el10_2.x86_64 from ubi-10-baseos-rpms requires (glibc-gconv-extra(x86-64) = 2.39-121.el10_2 if redhat-rpm-config), but none of the providers can be installed
  - conflicting requests
```

Related: https://redhat.atlassian.net/browse/RHEL-178735