fix: make aegis work again with `ollama`
`ollama` does not accept `\d` in regular expressions, which results
in the following, difficult to debug, failure:
```
pydantic_ai.exceptions.ModelHTTPError: status_code: 400, model_name: mistral:7b-v3, body: {'code': 400, 'message': 'Failed to parse grammar', 'type': 'invalid_request_error'}
```

This was previously fixed in commit eaf44fce5298b2fbda4d4d9542f00de32dcbebb7
(in the `CVEID` model) but later, when the `CWEID` model became used in other
models and tools, the issue was reintroduced.

Related: commit eaf44fce5298b2fbda4d4d9542f00de32dcbebb7
Related: https://github.com/RedHatProductSecurity/aegis-ai/issues/146