fix: retry LLM prompt on `ModelHTTPError`, too
... to eliminate the following occasional failures:
```
FAILED evals/features/cve/test_suggest_cwe.py::test_eval_suggest_cwe - AssertionError: Unsatisfied assertion(s):
suggest-cwe-for-CVE-2025-49133: case failure: ModelHTTPError: status_code: 503, model_name: gemini-2.5-flash, body: {'error': {'code': 503, 'message': 'The model is overloaded. Please try again later.', 'status': 'UNAVAILABLE'}}
```

Related: commit ef7a261118325a593ebc72738a7475a4aebeb20f
Related: https://issues.redhat.com/browse/AEGIS-273