fix: make aegis work again with `ollama`
`ollama` does not accept `\d` in regular expressions, which results
in the following, difficult to debug, failure:
```
pydantic_ai.exceptions.ModelHTTPError: status_code: 400, model_name: mistral:7b-v3, body: {'code': 400, 'message': 'Failed to parse grammar', 'type': 'invalid_request_error'}
```

Note that if we apply this one-line patch on commit
6dbb422785cdbfca8d27de8bc7896e0dafc016c0, it does not fix the bug on its
own because the commit introduced other issues with `ollama`, which were
later fixed by commit 6bd3d2127cbc1e43f59e1fcefe5982d21fcc7c3d (although
the other commit is not tagged as a fix).

Fixes: commit 6dbb422785cdbfca8d27de8bc7896e0dafc016c0
Fixes: https://github.com/RedHatProductSecurity/aegis-ai/issues/146
Related: https://github.com/ollama/ollama/issues/10591
Related: https://issues.redhat.com/browse/AEGIS-118